[
build
]
  publish = "build"
  command = "npm run build"

# Redirect all page requests to index.html for SPA routing
[[
redirects
]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to Heroku backend
[[
redirects
]]
  from = "/api/*"
  to = "https://courtwatch-9dd3b16cc62c.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}